version: 2.1

orbs:
  nuget-cache: guitarrapc/nuget-cache@0.1.1
  aws-ecr: circleci/aws-ecr@3.0.0

executors:
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
  docker-python:
    docker:
      - image: circleci/python:3.7

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root     

jobs:
  check-code-formatting:
    executor: docker-dotnet
    steps:
      - checkout
      - run:
          name: Install dotnet format
          command: dotnet tool install dotnet-format --tool-path ./dotnet-format-local/
      - run:
          name: Run formatter check
          command: ./dotnet-format-local/dotnet-format --check Hackney.Shared.Tenure
  # build-and-test:
  #   executor: docker-python
  #   steps:
  #     - checkout
  #     - setup_remote_docker
  #     - run:
  #         name: build
  #         command: docker-compose build hackney-shared-person-test
  #     - run:
  #         name: Run tests
  #         command: docker-compose run hackney-shared-person-test
  publish-package:
    executor: docker-dotnet
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Release the Package          
          command: | 
            cd ./Hackney.Shared.Tenure
            dotnet pack --configuration Release
      - run: 
          name: Publish to GitHub
          command: |
            cd /root/project/Hackney.Shared.Tenure/bin/Release
            dotnet nuget push Hackney.Shared.Tenure.*.nupkg -s https://nuget.pkg.github.com/LBHackney-IT/index.json --api-key ${NUGET_KEY} Hackney.Shared.Tenure.*/*.nupkg
workflows:
   nuget-package:
    jobs:
      - check-code-formatting
      # - build-and-test
      - publish-package
          requires:
            - check-code-formatting
          filters:
            branches:
              only: release
          